spring.application.name=Pharma
# Tag : mysql db url
spring.datasource.url=jdbc:mysql://localhost:3306/pharma
spring.datasource.username=root
spring.datasource.password=hari@1494

# Tag : mysql drivers
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform = org.hibernate.dialect.MySQLDialect
spring.jpa.generate-ddl=true


# Tag : show sql queries in console
spring.jpa.show-sql=true

# Tag :db records store
spring.jpa.hibernate.ddl-auto = create-drop
spring.jpa.properties.hibernate.format_sql=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=shreeharineshs@gmail.com
spring.mail.password=zcbdetuyfkqhxube
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true